DROP TABLE COUNTRIES CASCADE;
DROP TABLE AIRLINES CASCADE;
DROP TABLE CITIES CASCADE;
DROP TABLE MAPS;
DROP TABLE FLIGHTS CASCADE;
DROP TABLE FLIGHTAVAILABILITY;
DROP TABLE FLIGHTS_HISTORY;
DROP INDEX DESTINDEX;
DROP INDEX ORIGINDEX;